plugins {
	id 'maven-publish'
	id 'fabric-loom' version '1.17.20'
	id 'babric-loom-extension' version '1.17.2'
}

version = property("mod_version")
group = property("maven_group")

base {
	archivesName = project.archives_base_name
}

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
	}
	withSourcesJar()
}

loom {
	mixin {
		useLegacyMixinAp = false
	}
}

repositories {
	// Used for the fabric toolchain in this project.
	maven {
		name = 'Babric'
		url = 'https://maven.glass-launcher.net/babric'
	}
	
	// Used for mappings.
	maven {
		name = 'Glass Releases'
		url = 'https://maven.glass-launcher.net/releases'
	}
	
	// Used for StationAPI and HowManyItems.
	maven {
		name = 'Glass Snapshots'
		url = 'https://maven.glass-launcher.net/snapshots'
	}
	
	// Used for a StationAPI dependency.
	maven {
		name = 'Froge'
		url 'https://maven.minecraftforge.net/'
	}
	
	// Used for projects that do not have a maven repository, but do have a GitHub repository with working build scripts.
	maven {
		name = 'Jitpack'
		url = 'https://jitpack.io'
	}
	
	// Used for another StationAPI dependency
	exclusiveContent {
		forRepository {
			maven {
				name = "Modrinth"
				url = "https://api.modrinth.com/maven"
			}
		}
		filter {
			includeGroup "maven.modrinth"
		}
	}
	
	mavenCentral()
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	mappings "net.glasslauncher:biny:${project.yarn_mappings}:v2"
	modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"

	implementation "org.slf4j:slf4j-api:1.8.0-beta4"
	implementation "org.apache.logging.log4j:log4j-slf4j18-impl:2.17.2"
	implementation(include("me.carleslc:Simple-Yaml:1.8.4") as Dependency)

	modImplementation("net.modificationstation:StationAPI:${project.stapi_version}") {
		exclude group: "babric", module: "fabric-loader"
	}

	// Optional, but convenient mods for mod creators and users alike.
	modImplementation("net.danygames2014:modmenu:${project.modmenu_version}") {
		transitive = false
	}

	modImplementation("net.glasslauncher.mods:glass-networking:${project.glass_networking_version}") {
		transitive = false
	}

	modImplementation("net.glasslauncher.mods:GlassConfigAPI:${project.gcapi_version}") {
		transitive = false
	}

	modImplementation("net.glasslauncher.mods:AlwaysMoreItems:${project.alwaysmoreitems_version}") {
		transitive = false
	}
}

processResources {
	inputs.property "version", project.version

	filesMatching("fabric.mod.json") {
		expand "version": project.version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 17
}

// Disables the generation of the .module file
tasks.withType(GenerateModuleMetadata).configureEach {
	enabled = false
}

// Gradle 9 fails the build if there are no tests, but we are using the test package for a test mod
tasks.withType(Test).configureEach {
	failOnNoDiscoveredTests = false
}

jar {
	from("LICENSE") {
		rename { "${it}_" + base.archivesName.get() }
	}
}

// configure the maven publication
publishing {
	publications {
		mavenJava(MavenPublication) {
			from components.java
		}
	}

	repositories {
		
	}
}
